### ISSUE TITLE
Contribute on GitHub! link is invalid

### ISSUE THREAD

**Issue by dnebing** [liferay-design/blueprints#10]
When I click on the link, which points to https://github.com/liferay-design/blueprints/tree/working-file/src/pages/docs/guidelines/logo-usage.md I get a 404.

**Comment by dnebing** [comment]
Was on the Logos page, which I think is supposed to be the index.md file, not logo-usage.md.

**Comment by plhnk** [comment]
Thanks @dnebing — when I added the auth layer, I forgot to update the filepath in this component! Fix will be deployed soon
